name: Test and build artifacts on release

on:
  create:
    branches:
      - releases/*

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

jobs:
 build_apk_aab:
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
     - name: Checkout keystore repository
       uses: actions/checkout@v3
       with:
        repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore
        
     - name: Run tests and build release artifacts
       run: |
         ./gradlew test
         ./gradlew assembleRelease --stacktrace
         ./gradlew bundleRelease
         
     - name: Upload signed APK
       uses: actions/upload-artifact@v2
       with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release.apk
         
     - name: Upload AAB Bundle
       uses: actions/upload-artifact@v2
       with:
         name: app-release.aab
         path: app/build/outputs/bundle/release/app-release.aab
